### ISSUE TITLE
KeyError: "Recognizer3D: 'SwinTransformer3D is not in the models registry'"

### ISSUE THREAD

**Issue by Note-Liu** [SwinTransformer/Video-Swin-Transformer#1]
when i use :
python tools/train.py configs/recognition/swin/swin_base_patch244_window877_kinetics400_22k.py

an error occurred:

Traceback (most recent call last):
  File "tools/train.py", line 199, in <module>
    main()
  File "tools/train.py", line 154, in main
    model = build_model(
  File "/home/pytorch/lib/python3/site-packages/mmaction/models/builder.py", line 70, in build_model
    return build_localizer(cfg)
  File "/home/pytorch/lib/python3/site-packages/mmaction/models/builder.py", line 62, in build_localizer
    return LOCALIZERS.build(cfg)
  File "/home/pytorch/lib/python3/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/pytorch/lib/python3/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/pytorch/lib/python3/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "Recognizer3D: 'SwinTransformer3D is not in the models registry'"

How to solve it?

**Comment by erictang000** [comment]
I'm running into this as well - wondering how you resolved this?

**Comment by krag-harsh** [comment]
I am facing the same issue :(

**Comment by haofanwang** [comment]
I meet the same case

**Comment by LiDenglan** [comment]
run python setup.py develop

**Comment by caltonhao** [comment]
In my opinion, this bag "/home/pytorch/lib/python3/site-packages/mmaction" conflicts with "/Video-Swin-Transformer/mmaction". Python will call the former by default，so I just run "pip uninstall mmaction2" to uninstall the former one.

**Comment by LiDenglan** [comment]
> In my opinion, this bag "/home/pytorch/lib/python3/site-packages/mmaction" conflicts with "/Video-Swin-Transformer/mmaction". Python will call the former by default，so I just run "pip uninstall mmaction2" to uninstall the former one.

I used this command "pip uninstall mmaction2", but I got other error 'batch_size should be a positive integer value, but got batch_size=0'. How can I solve this problem?

**Comment by caltonhao** [comment]
> > In my opinion, this bag "/home/pytorch/lib/python3/site-packages/mmaction" conflicts with "/Video-Swin-Transformer/mmaction". Python will call the former by default，so I just run "pip uninstall mmaction2" to uninstall the former one.
> 
> I used this command "pip uninstall mmaction2", but I got other error 'batch_size should be a positive integer value, but got batch_size=0'. How can I solve this problem?

Maybe the config file has some error

**Comment by LiDenglan** [comment]
> > > In my opinion, this bag "/home/pytorch/lib/python3/site-packages/mmaction" conflicts with "/Video-Swin-Transformer/mmaction". Python will call the former by default，so I just run "pip uninstall mmaction2" to uninstall the former one.
> > 
> > 
> > I used this command "pip uninstall mmaction2", but I got other error 'batch_size should be a positive integer value, but got batch_size=0'. How can I solve this problem?
> 
> Maybe the config file has some error



> > > In my opinion, this bag "/home/pytorch/lib/python3/site-packages/mmaction" conflicts with "/Video-Swin-Transformer/mmaction". Python will call the former by default，so I just run "pip uninstall mmaction2" to uninstall the former one.
> > 
> > 
> > I used this command "pip uninstall mmaction2", but I got other error 'batch_size should be a positive integer value, but got batch_size=0'. How can I solve this problem?
> 
> Maybe the config file has some error

Could you send me your command which generate the config file?

**Comment by lyglxz** [comment]
> > In my opinion, this bag "/home/pytorch/lib/python3/site-packages/mmaction" conflicts with "/Video-Swin-Transformer/mmaction". Python will call the former by default，so I just run "pip uninstall mmaction2" to uninstall the former one.
> 
> I used this command "pip uninstall mmaction2", but I got other error 'batch_size should be a positive integer value, but got batch_size=0'. How can I solve this problem?

It seems that Video-Swin-Transformer/mmaction/apis/train.py:55 cause that problem. File Video-Swin-Transformer/configs/recognition/swin/swin_base_patch244_window877_kinetics400_22k.py
That line is dooing "videos_per_gpu = videos_per_gpu//update_interval", batch_size = num_gpus * videos_per_gpu
I found this error after error -- "shared memory insufficient", I change videos_per_gpu to 4 and got same error you met
