### ISSUE TITLE
Drop path rate

### ISSUE THREAD

**Issue by minostauros** [SwinTransformer/Video-Swin-Transformer#10]
Hi,

https://github.com/SwinTransformer/Video-Swin-Transformer/blob/db018fb8896251711791386bbd2127562fd8d6a6/configs/recognition/swin/swin_small_patch244_window877_kinetics400_1k.py#L4

Code claims Swin small uses 0.1 drop path rate, but does it match with the [report](https://arxiv.org/abs/2106.13230) which reads 0.2?
Swin-T and Swin-B uses 0.1, and 0.3 respectively as follows:

https://github.com/SwinTransformer/Video-Swin-Transformer/blob/db018fb8896251711791386bbd2127562fd8d6a6/configs/recognition/swin/swin_tiny_patch244_window877_kinetics400_1k.py#L4
https://github.com/SwinTransformer/Video-Swin-Transformer/blob/db018fb8896251711791386bbd2127562fd8d6a6/configs/recognition/swin/swin_base_patch244_window877_kinetics400_1k.py#L4

Thanks,

**Comment by hust-nj** [comment]
Hi, drop path rate of small model is 0.1, just a clerical error in paper, we will update it in next version.
