### ISSUE TITLE
What head to use ? 

### ISSUE THREAD

**Issue by Scienceseb** [SwinTransformer/Video-Swin-Transformer#11]
Hi! 

There is a problem with the Video Swin Transformer code at the moment, as it is done in a way that makes it impossible to change the number of target classes in an end-to-end fashion. Wanting to use your model on another dataset containing for example 10 or 50 classes, the network gives me an output for the head. 

I build a model: 
```
model_VST = SwinTransformer3D()
model_VST.cuda()

```
You can see that I don't have any class number argument in the template paranthese, indeed your code doesn't take that as an argument. Here are the argumentsthat your Video Swin Transformer model takes as input:  
There is nothing  for the number of target classes. Right now for an input shape of torch.Size([1, 8, 3, 64, 64]), I get an output shape of torch.Size([1, 768, 2, 2, 2]) from the model_VST (which is the SwinTransformer3D).  

**I understand that I need to add an head to it, but it is not clear at all in your code how to properly manage that. What head to use ? ** 

Maybe you can make something like Facebook did with their TimeSformer, they made an end-to-end version of it for classification of videos.

**Comment by hust-nj** [comment]
Hi, we include head config here
https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/configs/_base_/models/swin/swin_tiny.py#L18-L23
