### ISSUE TITLE
Keeping the temporal dimension

### ISSUE THREAD

**Issue by hongsukchoi** [SwinTransformer/Video-Swin-Transformer#12]
Hi, thanks for your fascinating work!

I want to use the video swin transfomer as a backbone, but my model should produce an output for each input frame.
Thus I want to keep the temporal dimension of input after the forward pass.

So I'm thinking of changing the parameter like this `patch_size=(1,4,4)`, but I am concerned about whether this could violate the authors' intention to make spatio-temporal feature.

Apart from the memory usage issue, is it okay to make the temporal window size of the patch embedding to 1?

**Comment by hust-nj** [comment]
You can try it, we test some cases and find changing `patch_size=(1,4,4)` can always improve the performance with the cost of increasing memory and flops.
