### ISSUE TITLE
Where can I find the <PRETRAIN_MODEL>?

### ISSUE THREAD

**Issue by wsh-nie** [SwinTransformer/Video-Swin-Transformer#13]
Hi, thanks for this fascinating work!
I want to follow the instructions `bash tools/dist_train.sh <CONFIG_FILE> <GPU_NUM> --cfg-options load_from=<PRETRAIN_MODEL> [model.backbone.use_checkpoint=True] [other optional arguments]` to run the program, but I don't know where I can find the pretrain model. 
So, I need some help, thanks all of you!

**Comment by r-kellerm** [comment]
You can find the pretrained models in the column "model" for each dataset, under https://github.com/SwinTransformer/Video-Swin-Transformer.
E.g. 
![image](https://user-images.githubusercontent.com/34206121/131336413-7e731d99-207a-4841-abd5-62d4b6531be7.png)

**Comment by hust-nj** [comment]
@wsh-nie We included pretrained model link in readme
![image](https://user-images.githubusercontent.com/27663478/132312512-fb1d623c-dab2-4085-bdc2-5c9145b24bda.png)

**Comment by AnupKumarGupta** [comment]
The Baidu shows incorrect credentials for the code `swim`.

**Comment by hayleeXinyi** [comment]
Hi, are there any mismatches occurring? I find that when I set it as below I can inference normally

```
config_file = '/home/haylee/Video-Swin-Transformer/mmaction2/tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb.py'
checkpoint_file = '/home/haylee/Video-Swin-Transformer/mmaction2/tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb_20220906-2692d16c.pth'
```

But setting it to the following reasoning reports an error

```
config_file = '/home/haylee/Video-Swin-Transformer/configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py'
checkpoint_file = '/home/haylee/Video-Swin-Transformer/checkpoints/tsn_r50_1x1x3_100e_kinetics400_rgb_20200614-e508be42.pth'
```
Error as below:
```
Exception has occurred: TypeError
class 'Normalize' in mmcv/transforms/processing.py: Normalize.__init__() got an unexpected keyword argument 'to_bgr'
TypeError: Normalize.__init__() got an unexpected keyword argument 'to_bgr'

During handling of the above exception, another exception occurred:

  File "/home/haylee/Video-Swin-Transformer/mmaction2/mmaction/apis/inference.py", line 79, in inference_recognizer
    test_pipeline = Compose(test_pipeline_cfg)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haylee/Video-Swin-Transformer/demo/haylee_demo.py", line 12, in <module>
    pred_result = inference_recognizer(model, video_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: class 'Normalize' in mmcv/transforms/processing.py: Normalize.__init__() got an unexpected keyword argument 'to_bgr'

```
