### ISSUE TITLE
How long does it take to train an epoch with SWIN-B?

### ISSUE THREAD

**Issue by Christinepan881** [SwinTransformer/Video-Swin-Transformer#14]
I used swin-B to train on the epic-kitchens dataset, but it takes me almost 27 hours for one epoch training (mixed precision was already applied).
I used 4 V100 GPUs, batch_size=8. 
Is this the normal time for training?

**Comment by hust-nj** [comment]
Hi, your training time must be abnormal, training Swin-B on kinetics400 for 1 epoch only spends 2 hours on 8 v100 cards.
