### ISSUE TITLE
About the 3D relative position bias

### ISSUE THREAD

**Issue by TangMinLeo** [SwinTransformer/Video-Swin-Transformer#16]
In the subsection 3D relative position bias of your paper, a bias is added in the self-attention computaion.
I don't fully understand it.
![Image_20210826162825](https://user-images.githubusercontent.com/53674565/130929408-b2b864d6-b115-4936-bdc4-26f1f0fa1ce6.png)

According to your description,  Q,K,V are all matrices with _P*M^2_ rows and _d_ columns, so _QK^T_ will be a square matrix with  _P*M^2_ rows and _P*M^2_ columns.  To make the summation valid,  the 3D relative position bias _B_ should also be a square matrix wtih _P*M^2_ rows and _P*M^2_ columns.  So how are the values in B are set? Specifically, how the member B(i,j) of B is set ?
I can't get any link between B and ![Image_20210826175012](https://user-images.githubusercontent.com/53674565/130942078-c84577ec-3349-4e54-8fa5-164ff5143794.png)

**Comment by TangMinLeo** [comment]
a few days later, I understand it !

**Comment by hust-nj** [comment]
Close because of solved.
