### ISSUE TITLE
modify the config file 

### ISSUE THREAD

**Issue by Note-Liu** [SwinTransformer/Video-Swin-Transformer#2]
when i use swin_base_patch244_window877_kinetics400_22k  to train my dataset, the config file:

# dataset settings
dataset_type = 'VideoDataset'
data_root = 'data/kinetics400/train'
data_root_val = 'data/kinetics400/val'
ann_file_train = 'data/kinetics400/kinetics400_train_list.txt'
ann_file_val = 'data/kinetics400/kinetics400_val_list.txt'
ann_file_test = 'data/kinetics400/kinetics400_val_list.txt'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False)
train_pipeline = [
    dict(type='DecordInit'),
    dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1),
    dict(type='DecordDecode'),
    dict(type='Resize', scale=(-1, 256)),
    dict(type='RandomResizedCrop'),
    dict(type='Resize', scale=(224, 224), keep_ratio=False),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]

because my frame txt format is :

        some/directory-1 163 1
        some/directory-2 122 1
        some/directory-3 258 2
        some/directory-4 234 2
        some/directory-5 295 3
        some/directory-6 121 3

I want to change dataset_type = 'RawframeDataset',  do i need modify "dict(type='DecordInit')" ?

**Comment by TitaniumOne** [comment]
> when i use swin_base_patch244_window877_kinetics400_22k to train my dataset, the config file:
> # dataset settings
> 
> dataset_type = 'VideoDataset' data_root = 'data/kinetics400/train' data_root_val = 'data/kinetics400/val' ann_file_train = 'data/kinetics400/kinetics400_train_list.txt' ann_file_val = 'data/kinetics400/kinetics400_val_list.txt' ann_file_test = 'data/kinetics400/kinetics400_val_list.txt' img_norm_cfg = dict( mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_bgr=False) train_pipeline = [ dict(type='DecordInit'), dict(type='SampleFrames', clip_len=32, frame_interval=2, num_clips=1), dict(type='DecordDecode'), dict(type='Resize', scale=(-1, 256)), dict(type='RandomResizedCrop'), dict(type='Resize', scale=(224, 224), keep_ratio=False), dict(type='Flip', flip_ratio=0.5), dict(type='Normalize', **img_norm_cfg), dict(type='FormatShape', input_format='NCTHW'), dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]), dict(type='ToTensor', keys=['imgs', 'label']) ]
> 
> because my frame txt format is :
> 
> ```
>     some/directory-1 163 1
>     some/directory-2 122 1
>     some/directory-3 258 2
>     some/directory-4 234 2
>     some/directory-5 295 3
>     some/directory-6 121 3
> ```
> 
> I want to change dataset_type = 'RawframeDataset', do i need modify "dict(type='DecordInit')" ?

Hello! My dataset format is like yours, could you share your config file?
Thank you very much!
