### ISSUE TITLE
Inaccessible Download Links

### ISSUE THREAD

**Issue by RaivoKoot** [SwinTransformer/Video-Swin-Transformer#32]
The download links for Kinetics 400 pretrained models are on pan.baid.com. Many people are not able to download these at all because you need to create an account (with a phone number) to download files from that site. If you are in germany or the UK, like me, it is not possible to create an account to download these. Please host them somewhere else to make them available to the general public.

**Comment by hust-nj** [comment]
Hi, we provide github link for global user and Baidu for Chinese user only, please check the github link.

**Comment by RaivoKoot** [comment]
Thank you!
