### ISSUE TITLE
the training iteration is abnormally large

### ISSUE THREAD

**Issue by bolin-chen** [SwinTransformer/Video-Swin-Transformer#42]
I used 4 gpus(2080ti) to train swin_small with config `swin_small_patch244_window877_kinetics400_1k.py`. The dataset I used is hacs(50w videos). The following is some of my training log:

![image](https://user-images.githubusercontent.com/7379489/148008285-188c8491-4a1e-4c7a-92ae-ca9d45961256.png)

I find that the train iteration is abnormally large based on my config(dataset size(50w) and batch_size(8)), which leads to the long training time. Is that normal?

**Comment by MartinXM** [comment]
Check your optimizer_config, set update_interval=1 if your GPU memory is large enough, it would make your training faster.

**Comment by bolin-chen** [comment]
Get it. It seems that the actual batch size is batch_size / update_interval.
