### ISSUE TITLE
AttributeError: Module tools/data/kinetics/label_map_k400.txt not found

### ISSUE THREAD

**Issue by minertom** [SwinTransformer/Video-Swin-Transformer#44]
I got to the end of the installation and was running the script to do the check to see if installation was done correctly.

In the open_mmlab environment, the very last line of the script
`inference_recognizer(model, 'demo/demo.mp4', 'demo/label_map_k400.txt')`
received an error
`AttributeError: 'Recognizer2D' object has no attribute 'demo/label_map_k400'`

How to proceed?

Thank You
Tom

**Comment by cybershiptrooper** [comment]
How did you resolve this?

**Comment by sbenslan** [comment]
having same issue, how did you fix it?
Cheers Sebastian

**Comment by Unnnncode** [comment]
how to solve the issue
