### ISSUE TITLE
About learning rate and batch size

### ISSUE THREAD

**Issue by geek12138** [SwinTransformer/Video-Swin-Transformer#59]
For the original configuration file, is it all 8 GPU configurations?

Specifically, is the base_22k model on 8 GPUs with a batch size of 8 and a learning rate of 3e-4?
For others, is the model on 8 GPUs with a batch size of 8 and a learning rate of 1e-3?

**Comment by hust-nj** [comment]
> For the original configuration file, is it all 8 GPU configurations?
> 
> Specifically, is the base_22k model on 8 GPUs with a batch size of 8 and a learning rate of 3e-4? For others, is the model on 8 GPUs with a batch size of 8 and a learning rate of 1e-3?

Yes, you are right

**Comment by geek12138** [comment]
Thank you
