### ISSUE TITLE
About the input image shape

### ISSUE THREAD

**Issue by Chen-Bo-Yang** [SwinTransformer/Video-Swin-Transformer#69]
I get the image shape from dataloader, the image shape is torch.Size([1, 12, 3, 32, 224, 224]).
I know it's [batch_size, ?, RGB, frames, H, W], but I don't know why it has "12" in a video data.
Does anyone know that dimension is?

In ./tools/test.py:
    data_loader = build_dataloader(dataset, **dataloader_setting)
    for i in data_loader:
        print("img shape: ", i['imgs'].size())

Thank you.

**Comment by fringe-k** [comment]
Hi, I am also confused about this. Do you have any answers?

**Comment by Chen-Bo-Yang** [comment]
> Hi, I am also confused about this. Do you have any answers?

Hello, I find the answer in the following path: 
SwinTransformer/Video-Swin-Transformer/configs/recognition/swin/swin_tiny_patch244_window877_kinetics400_1k.py

You can see that in "test_pipeline" have two process, one is SampleFrames(num_clips=4), another is ThreeCrop.
So it generates 4x3 clips for testing.
