### ISSUE TITLE
Which version of Kinetics400 do you use?

### ISSUE THREAD

**Issue by yxchng** [SwinTransformer/Video-Swin-Transformer#8]
There are many different version of kinetics 400 and some has more videos than others. Can I know which version do you use and what is the statistics of your train and test set, i.e. how many train and test videos do you have?

**Comment by hust-nj** [comment]
Hi, thanks for your interest, we share the kinetics400 annotation here: https://github.com/SwinTransformer/storage/releases/tag/v1.0.6
