### ISSUE TITLE
swin config file work_dir = work_dir  = ..?

### ISSUE THREAD

**Issue by g1910** [SwinTransformer/Video-Swin-Transformer#9]
Why does the swin transformer config files have work_dir = work_dir = ... at https://github.com/SwinTransformer/Video-Swin-Transformer/blob/d13b5a30ce1d2398c376f228ab43759ebbe601d5/configs/recognition/swin/swin_base_patch244_window877_kinetics400_22k.py#L109

**Comment by hust-nj** [comment]
Fixed, thanks :)
